spring:
    cache:
        type: redis
        redis:
            host: 127.0.0.1
            port: 6379
#        password: 123321
#        配置文件中修改ttl
#            time-to-live: 36000
            lettuce:
                pool:
                    max-active: 8
                    max-idle: 8
                    min-idle: 0
                    max-wait: 100ms