spring:
    redis:
        host: 127.0.0.1
        port: 6379
#        password: 123321
        lettuce:
            pool:
                max-active: 8
                max-idle: 8
                min-idle: 0
                max-wait: 100ms