server:
    port: 8080
spring:
    application:
        name: user-cache
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/user-cache?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 123456
    cache:
        type: redis
    data:
        redis:
            host: 127.0.0.1
            port: 6666
#           允许缓存null值
            cache-null-values: true
#        password: 123321
#        配置文件中修改ttl
#            time-to-live: 36000
            lettuce:
                pool:
                    max-active: 8
                    max-idle: 8
                    min-idle: 0
                    max-wait: 100ms
mybatis:
    #mapper配置文件
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.buercorp.wangyu
    configuration:
        #开启驼峰命名
        map-underscore-to-camel-case: true