logging:
    level:
        io.lettuce.core: debug
    pattern:
        dateformat: MM-dd HH:mm:ss:SSS

spring:
    redis:
        #        sentinel:
        #            master: mymaster
        #            nodes:
        #                - 192.168.0.20:27001
        #                - 192.168.0.20:27002
        #                - 192.168.0.20:27003
        cluster:
        nodes:
            - 192.168.150.101:7001
            - 192.168.150.101:7002
            - 192.168.150.101:7003
            - 192.168.150.101:8001
            - 192.168.150.101:8002
            - 192.168.150.101:8003